<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PortfolioProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = [
            [
                'id' => 1,
                'title' => 'The Art Collector Private Residence',
                'type_id' => 1,
                'completion_date' => '2023-06-15',
                'architects' => json_encode(['Zaher Bissar']),
                'year' => 2022,
                'location' => 'Riyadh',
                'description' => 'One of the first assignments for us is to set the inspiration for the project; we invest a tremendous amount of time seeking inspiration from our client’s lifestyle and personal tastes. Aware of our client’s interest in fine art, we have selected masterpieces from the most prestigious galleries in the world. The warm and textured wooden high walls has created the perfect background for these art pieces. This project with fortunate high ceilings was transformed into a hidden museum in a private home.',
                'banner' => url('/images/projects/portfolio/the_collector_private_residence/banners/banner1.webp'),
                'thumbnail' => url('/images/projects/portfolio/the_collector_private_residence/thumbnails/works1.webp'),
                'images' => json_encode([
                    url('/images/projects/portfolio/the_collector_private_residence/images/Rectangle 7.webp'),
                    url('/images/projects/portfolio/the_collector_private_residence/images/Rectangle 9.webp'),
                    url('/images/projects/portfolio/the_collector_private_residence/images/Rectangle 11.webp'),
                    url('/images/projects/portfolio/the_collector_private_residence/images/Rectangle 12.webp'),
                    url('/images/projects/portfolio/the_collector_private_residence/images/Rectangle 14.webp'),
                    url('/images/projects/portfolio/the_collector_private_residence/images/Rectangle 15.webp'),
                    url('/images/projects/portfolio/the_collector_private_residence/images/Rectangle 10.webp'),
                    url('/images/projects/portfolio/the_collector_private_residence/images/Rectangle 13.webp'),
                    url('/images/projects/portfolio/the_collector_private_residence/images/Rectangle 16.webp'),
                ]),
                'client' => 'Private',
                'slug' => 'the-art-collector-private-residence',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'title' => 'Al Rawda Reception Villa',
                'type_id' => 2,
                'completion_date' => '2020-11-08',
                'architects' => json_encode(['Zaher Bissar']),
                'year' => 2020,
                'location' => 'Riyadh',
                'description' => 'This gorgeous 1270 m² project in Riyadh is the family reception villa that makes part of an extensive private complex. It is a beautiful example of a luxury contemporary home, infused with Islamic influences that resonate with its vibrant heritage. Original orientalism paintings, crafted antiques, Islamic patterns and intricate noble materials accentuate the identity of the place.',
                'banner' => url('/images/projects/portfolio/al_rawda_reception_villa/banners/banner2.webp'),
                'thumbnail' => url('/images/projects/portfolio/al_rawda_reception_villa/thumbnails/works2.webp'),
                'images' => json_encode([
                    url('/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 17.webp'),
                    url('/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 18.webp'),
                    url('/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 20.webp'),
                    url('/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 23.webp'),
                    url('/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 24.webp'),
                    url('/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 19.webp'),
                    url('/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 25.webp'),
                    url('/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 26.webp'),
                ]),
                'client' => 'Private',
                'slug' => 'al-rawda-private-residence',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'title' => 'Al Ghadir Villa',
                'type_id' => 2,
                'completion_date' => '2019-09-23',
                'architects' => json_encode(['Zaher Bissar']),
                'year' => 2019,
                'location' => 'Riyadh',
                'description' => 'The exclusive interior design of this spacious project that impresses with the elegance and splendor of the timeless furniture pieces is the reception area of this villa. The focal point of this project is a double height space, where a crystal light installation from floor to ceiling is stretching out from floor to ceiling. This piece is called the “Crystal Biosphere”.',
                'banner' => url('/images/projects/portfolio/al_ghadir_villa/banners/banner3.webp'),
                'thumbnail' => url('/images/projects/portfolio/al_ghadir_villa/thumbnails/works3.webp'),
                'images' => json_encode([
                    url('/images/projects/portfolio/al_ghadir_villa/images/Rectangle 27.webp'),
                    url('/images/projects/portfolio/al_ghadir_villa/images/Rectangle 28.webp'),
                    url('/images/projects/portfolio/al_ghadir_villa/images/Rectangle 30.webp'),
                    url('/images/projects/portfolio/al_ghadir_villa/images/Rectangle 31.webp'),
                    url('/images/projects/portfolio/al_ghadir_villa/images/Rectangle 35.webp'),
                    url('/images/projects/portfolio/al_ghadir_villa/images/Rectangle 36.webp'),
                    url('/images/projects/portfolio/al_ghadir_villa/images/Rectangle 38.webp'),
                    url('/images/projects/portfolio/al_ghadir_villa/images/Rectangle 29.webp'),
                    url('/images/projects/portfolio/al_ghadir_villa/images/Rectangle 32.webp'),
                    url('/images/projects/portfolio/al_ghadir_villa/images/Rectangle 37.webp'),
                    url('/images/projects/portfolio/al_ghadir_villa/images/Rectangle 39.webp'),
                ]),
                'client' => 'Private',
                'slug' => 'al-ghadir-villa',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'title' => 'Al Rawda Private Residence',
                'type_id' => 2,
                'completion_date' => '2021-05-17',
                'architects' => json_encode(['Zaher Bissar']),
                'year' => 2021,
                'location' => 'Riyadh',
                'description' => 'This luxury private suite combines exquisite, complex detail work with statement prints and muted walls for a modern Asian inspired aesthetic. Three different wallpapers by “De Gournay” are the catchiest elements in this project. Once again, we went in search of the top furniture brands and unique pieces from different European Galleries. A rich color palette is used throughout, giving a sense of depth to the contemporary space; while accent colors and gold hues add a warm splash of color into the design.',
                'banner' => url('/images/projects/portfolio/al_rawda_private_residence/banners/banner4.webp'),
                'thumbnail' => url('/images/projects/portfolio/al_rawda_private_residence/thumbnails/works4.webp'),
                'images' => json_encode([
                    url('/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 40.webp'),
                    url('/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 42.webp'),
                    url('/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 43.webp'),
                    url('/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 44.webp'),
                    url('/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 45.webp'),
                    url('/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 49.webp'),
                    url('/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 41.webp'),
                    url('/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 46.webp'),
                    url('/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 47.webp'),
                ]),
                'client' => 'Private',
                'slug' => 'al-rawda-private-residence',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'title' => 'The Sisters Villa',
                'type_id' => 3,
                'completion_date' => '2019-12-01',
                'architects' => json_encode(['Zaher Bissar']),
                'year' => 2018,
                'location' => 'Riyadh',
                'banner' => url('/images/projects/portfolio/the_sisters_villa/banners/banner5.webp'),
                'thumbnail' => url('/images/projects/portfolio/the_sisters_villa/thumbnails/works5.webp'),
                'images' => json_encode([
                    url('/images/projects/portfolio/the_sisters_villa/images/Rectangle 50.webp'),
                    url('/images/projects/portfolio/the_sisters_villa/images/Rectangle 51.webp'),
                    url('/images/projects/portfolio/the_sisters_villa/images/Rectangle 53.webp'),
                    url('/images/projects/portfolio/the_sisters_villa/images/Rectangle 54.webp'),
                    url('/images/projects/portfolio/the_sisters_villa/images/Rectangle 55.webp'),
                    url('/images/projects/portfolio/the_sisters_villa/images/Rectangle 56.webp'),
                    url('/images/projects/portfolio/the_sisters_villa/images/Rectangle 57.webp'),
                    url('/images/projects/portfolio/the_sisters_villa/images/Rectangle 58.webp'),
                ]),
                'client' => 'Private',
                'description' => 'Project is a modern luxury interpretation of Saudi lifestyle. Developed as a personal signature space, the design embraces 10m high walls, large windows, open layout, giving a bright & refreshing vibe. Natural stone was chosen to provide a solid neutral base, where every corner of the house stands as a distinct space. Earthy elements of natural wood, light textiles, and leather together with modern art and massive sculptures from local artists were blended into a serene minimalistic aesthetic.',
                'slug' => 'the-sisters-villa',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'title' => 'Jenadriah Farm',
                'type' => 'Pool House',
                'completion_date' => '2018-07-29',
                'architects' => json_encode(['Zaher Bissar']),
                'year' => 2022,
                'location' => 'Riyadh',
                'description' => 'Layered textures, earthy tones, hints of sleek patterns, and crochet accents with bold natural wood are just what you need for achieving a Boho-Chic look. The focal point is a wooden backdrop versus expansive glass walls overlooking the pool and its green surroundings. This pool house is a free-standing building in the middle of an extensive green area; the farm is located in Janadriah, a suburb of Riyadh city.',
                'banner' => url('/images/projects/portfolio/jenadriah_villa/banners/banner6.webp'),
                'thumbnail' => url('/images/projects/portfolio/jenadriah_villa/thumbnails/works6.webp'),
                'images' => json_encode([
                    url('/images/projects/portfolio/jenadriah_villa/images/Rectangle 62.webp'),
                    url('/images/projects/portfolio/jenadriah_villa/images/Rectangle 63.webp'),
                    url('/images/projects/portfolio/jenadriah_villa/images/Rectangle 64.webp'),
                    url('/images/projects/portfolio/jenadriah_villa/images/Rectangle 65.webp'),
                    url('/images/projects/portfolio/jenadriah_villa/images/Rectangle 66.webp'),
                    url('/images/projects/portfolio/jenadriah_villa/images/Rectangle 67.webp'),
                ]),
                'client' => 'Private',
                'slug' => 'jenadriah-farm',
                'category' => 'Portfolio',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'title' => 'Modern Loft',
                'type_id' => 4,
                'completion_date' => '2021-04-20',
                'architects' => json_encode(['Zaher Bissar']),
                'year' => 2021,
                'location' => 'Seattle, WA',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
                'banner' => url('/images/innerhero/projectdetails.webp'),
                'thumbnail' => url('/images/projects/portfolio/thumbnails/works1.webp'),
                'images' => json_encode([
                    url('/images/projects/portfolio/images/image.webp'),
                    url('/images/projects/portfolio/images/image.webp'),
                    url('/images/projects/portfolio/images/image.webp'),
                    url('/images/projects/portfolio/images/image.webp'),
                    url('/images/projects/portfolio/images/image.webp'),
                    url('/images/projects/portfolio/images/image.webp'),
                ]),
                'client' => 'Loft Living Co.',
                'slug' => 'modern-loft',
                'category_id' => 1,
                'created_at' => now(), // Set created_at to current timestamp
                'updated_at' => now(), // Optionally set updated_at to current timestamp
            ],
            [
                'id' => 8,
                'title' => 'Seaside Retreat',
                'type_id' => 2,
                'completion_date' => '2022-07-12',
                'architects' => json_encode(['Zaher Bissar']),
                'year' => 2022,
                'location' => 'Malibu, CA',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
                'banner' => url('/images/innerhero/projectdetails.webp'),
                'thumbnail' => url('/images/projects/portfolio/thumbnails/works2.webp'),
                'images' => json_encode([
                    url('/images/projects/portfolio/images/image.webp'),
                    url('/images/projects/portfolio/images/image.webp'),
                    url('/images/projects/portfolio/images/image.webp'),
                    url('/images/projects/portfolio/images/image.webp'),
                    url('/images/projects/portfolio/images/image.webp'),
                    url('/images/projects/portfolio/images/image.webp'),
                    url('/images/projects/portfolio/images/image.webp'),
                ]),
                'client' => 'Beachside Estates',
                'slug' => 'seaside-retreat',
                'category_id' => 1,
                'created_at' => now(), // Set created_at to current timestamp
                'updated_at' => now(), // Optionally set updated_at to current timestamp
            ],
            [
                'id' => 9,
                'title' => 'Penthouse Suite',
                'type_id' => 2,
                'completion_date' => '2023-01-10',
                'architects' => json_encode(['Zaher Bissar']),
                'year' => 2023,
                'location' => 'Dubai, UAE',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
                'banner' => url('/images/innerhero/projectdetails.webp'),
                'thumbnail' => url('/images/projects/portfolio/thumbnails/works3.webp'),
                'images' => json_encode([
                    url('/images/projects/portfolio/images/image.webp'),
                    url('/images/projects/portfolio/images/image.webp'),
                    url('/images/projects/portfolio/images/image.webp'),
                    url('/images/projects/portfolio/images/image.webp'),
                    url('/images/projects/portfolio/images/image.webp'),
                ]),
                'client' => 'Luxury Living Group',
                'slug' => 'penthouse-suite',
                'category_id' => 1,
                'created_at' => now(), // Set created_at to current timestamp
                'updated_at' => now(), // Optionally set updated_at to current timestamp
            ]        
        ];
        DB::table('portfolio_projects')->insert($projects);
    }
}