<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PortfolioProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = [
            [
                'id' => 1,
                'title' => 'The Art Collector Private Residence',
                'category' => 'Private Residence',
                'architects' => json_encode(['Zaher Bissar']),
                'year' => 2022,
                'location' => 'Riyadh',
                'description' => 'One of the first assignments for us is to set the inspiration for the project; we invest a tremendous amount of time seeking inspiration from our client’s lifestyle and personal tastes. Aware of our client’s interest in fine art, we have selected masterpieces from the most prestigious galleries in the world. The warm and textured wooden high walls has created the perfect background for these art pieces. This project with fortunate high ceilings was transformed into a hidden museum in a private home.',
                'banner' => asset('/images_v1/projects/portfolio/the_collector_private_residence/banners/banner1.jpg'),
                'thumbnail' => asset('/images_v1/projects/portfolio/the_collector_private_residence/thumbnails/works1.jpg'),
                'images' => json_encode([
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/001.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/002.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/003.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/004.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/010 (1).jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/010 (2).jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/021.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/022.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/023.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/025.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/026.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/027.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/030.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/031.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/040.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/041.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/042.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/043.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/044.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/045.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/050.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/051.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/052.jpg'),
                    asset('/images_v1/projects/portfolio/the_collector_private_residence/images/053.jpg'),
                ]),
                'client' => 'Private',
                'slug' => 'the-art-collector-private-residence',
                'type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
             ],
            [
                'id' => 2,
                'title' => 'Al Rawda Reception Villa',
                'category' => 'Family Home',
                'architects' => json_encode(['Zaher Bissar']),
                'year' => 2020,
                'location' => 'Riyadh',
                'description' => 'This gorgeous 1270 m² project in Riyadh is the family reception villa that makes part of an extensive private complex. It is a beautiful example of a luxury contemporary home, infused with Islamic influences that resonate with its vibrant heritage. Original orientalism paintings, crafted antiques, Islamic patterns and intricate noble materials accentuate the identity of the place.',
                'banner' => asset('/images_v1/projects/portfolio/al_rawda_reception_villa/banners/banner2.jpg'),
                'thumbnail' => asset('/images_v1/projects/portfolio/al_rawda_reception_villa/thumbnails/works2.jpg'),
                'images' => json_encode([
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/001.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/002.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/003.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/004.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/09.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/09 (1).jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/10 (1).jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/10 (3).jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/15.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/16.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/20.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/21.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/30.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/31.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/32.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/33.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/34.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/35.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/55 (1).jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/55 (2).jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/55 (3).jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/56.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/57.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/58.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/60.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/61.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/62.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/63.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/64.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_reception_villa/images/65.jpg'),
                ]),
                'client' => 'Private',
                'slug' => 'al-rawda-reception-villa',
                'type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'title' => 'Al Ghadir Villa',
                'category' => 'Family Home',
                'architects' => json_encode(['Zaher Bissar']),
                'year' => 2019,
                'location' => 'Riyadh',
                'description' => 'The exclusive interior design of this spacious project that impresses with the elegance and splendor of the timeless furniture pieces is the reception area of this villa. The focal point of this project is a double height space, where a crystal light installation from floor to ceiling is stretching out from floor to ceiling. This piece is called the “Crystal Biosphere”',
                'banner' => asset('/images_v1/projects/portfolio/al_ghadir_villa/banners/banner3.jpg'),
                'thumbnail' => asset('/images_v1/projects/portfolio/al_ghadir_villa/thumbnails/works3.jpg'),
                'images' => json_encode([
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/001.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/002.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/003.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/004.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/005.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/006.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/007.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/008.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/009.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/010.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/011.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/012.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/013.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/014.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/015.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/016.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/017.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/018.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/019.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/020.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/021.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/022.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/023.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/024.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/025.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/026.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/027.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/028.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/029.jpg'),
                    asset('/images_v1/projects/portfolio/al_ghadir_villa/images/030.jpg'),
                ]),
                'client' => 'Private',
                'slug' => 'al-ghadir-villa',
                'type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'title' => 'Al Rawda Private Residence',
                'category' => 'Family Home', 
                'architects' => json_encode(['Zaher Bissar']),
                'year' => 2021,
                'location' => 'Riyadh',
                'description' => 'This luxury private suite combines exquisite, complex detail work with statement prints and muted walls for a modern Asian inspired aesthetic. Three different wallpapers by “De Gournay” are the catchiest elements in this project. Once again, we went in search of the top furniture brands and unique pieces from different European Galleries. A rich color palette is used throughout, giving a sense of depth to the contemporary space; while accent colors and gold hues add a warm splash of color into the design.',
                'banner' => asset('/images_v1/projects/portfolio/al_rawda_private_residence/banners/banner4.jpg'),
                'thumbnail' => asset('/images_v1/projects/portfolio/al_rawda_private_residence/thumbnails/works4.jpg'),
                'images' => json_encode([
                    asset('/images_v1/projects/portfolio/al_rawda_private_residence/images/100.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_private_residence/images/101.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_private_residence/images/103.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_private_residence/images/201.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_private_residence/images/202.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_private_residence/images/204.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_private_residence/images/205.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_private_residence/images/300.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_private_residence/images/301.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_private_residence/images/302.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_private_residence/images/303.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_private_residence/images/401.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_private_residence/images/403.jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_private_residence/images/Asian (3).jpg'),
                    asset('/images_v1/projects/portfolio/al_rawda_private_residence/images/Asian (4).jpg'),
                ]),
                'client' => 'Private',
                'slug' => 'al-rawda-private-residence',
                'type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'title' => 'The Sisters Villa',
                'category' => 'Family Home', 
                'architects' => json_encode(['Zaher Bissar']),
                'year' => 2018,
                'location' => 'Riyadh',
                'description' => "From the first meeting the three sisters had a clear vision in mind: a stylish place that challenges the norms of residential design. The handsome style is a perfect blend of Luxury Contemporary and Urban Chic where plain walls and smart fabrics set the mood of the space. They are all tied together with one-of-a-kind furniture pieces and statement artworks. The ensemble aligns perfectly with the homeowner’s vision, taste and lifestyle. Have a look!",
                'banner' => asset('/images_v1/projects/portfolio/the_sisters_villa/banners/banner5.jpg'),
                'thumbnail' => asset('/images_v1/projects/portfolio/the_sisters_villa/thumbnails/works5.jpg'),
                'images' => json_encode([
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/01.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/02.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/03.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/04.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/05.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/07.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/200.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/210.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/211.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/212.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/213.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/215.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/220.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/221.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/225.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/230.jpg'),
                    asset('/images_v1/projects/portfolio/the_sisters_villa/images/235.jpg'),
                ]),
                'client' => 'Private',
                'slug' => 'the-sisters-villa',
                'type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'title' => 'Jenadriah Ranch',
                'category' => 'Pool House', 
                'architects' => json_encode(['Zaher Bissar']),
                'year' => 2022,
                'location' => 'Riyadh',
                'description' => 'Layered Textures, earthy tones, hints of sleek patterns and crochet accents with a bold natural wood are just what you need for achieving a Boho-Chic look. The focal point is a wooden backdrop versus expansive glass walls overlooking the pool and its green surrounding. This pool house is a free-standing building in the middle of an extensive green area; This ranch is located in Jenadriah, a suburb of Riyadh city.',
                'banner' => asset('/images_v1/projects/portfolio/jenadriah_ranch/banners/banner6.jpg'),
                'thumbnail' => asset('/images_v1/projects/portfolio/jenadriah_ranch/thumbnails/works6.jpg'),
                'images' => json_encode([
                    asset('/images_v1/projects/portfolio/jenadriah_ranch/images/000.jpg'),
                    asset('/images_v1/projects/portfolio/jenadriah_ranch/images/001.jpg'),
                    asset('/images_v1/projects/portfolio/jenadriah_ranch/images/03.jpg'),
                    asset('/images_v1/projects/portfolio/jenadriah_ranch/images/04.jpg'),
                    asset('/images_v1/projects/portfolio/jenadriah_ranch/images/05.jpg'),
                    asset('/images_v1/projects/portfolio/jenadriah_ranch/images/06.jpg'),
                    asset('/images_v1/projects/portfolio/jenadriah_ranch/images/07.jpg'),
                    asset('/images_v1/projects/portfolio/jenadriah_ranch/images/08.jpg'),
                    asset('/images_v1/projects/portfolio/jenadriah_ranch/images/09.jpg'),
                    asset('/images_v1/projects/portfolio/jenadriah_ranch/images/10.jpg'),
                ]),
                'client' => 'Private',
                'slug' => 'jenadriah_ranch',
                'type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('portfolio_projects')->insert($projects);
    }
}